[page.main]
name = "main"
path = "pages/intro/main.py"
icon = "ğŸ“š"
title = "Ğ“Ğ»Ğ°Ğ²Ğ½Ğ°Ñ ÑÑ‚Ñ€Ğ°Ğ½Ğ¸Ñ†Ğ°"
layout = "wide"
initial_sidebar_state = "auto"

[page.home]
name = "home"
path = "pages/home/home.py"
icon = "ğŸ“š"
title = "Ğ”Ğ¾Ğ¼Ğ°ÑˆĞ½ÑÑ ÑÑ‚Ñ€Ğ°Ğ½Ğ¸Ñ†Ğ°"
layout = "wide"
initial_sidebar_state = "auto"

[page.register]
name = "register"
path = "pages/auth/register.py"
icon = "ğŸ“"
title = "Ğ ĞµĞ³Ğ¸ÑÑ‚Ñ€Ğ°Ñ†Ğ¸Ñ"
layout = "wide"
initial_sidebar_state = "auto"