[[pages]]
path = "pages/intro/main.py"
name = "Ğ“Ğ»Ğ°Ğ²Ğ½Ğ°Ñ_ÑÑ‚Ñ€Ğ°Ğ½Ğ¸Ñ†Ğ°"
icon = "ğŸ“š"

[[pages]]
path = "pages/auth/registration_student.py"
name = "Ğ ĞµĞ³Ğ¸ÑÑ‚Ñ€Ğ°Ñ†Ğ¸Ñ_Ğ´Ğ»Ñ_ÑÑ‚ÑƒĞ´ĞµĞ½Ñ‚Ğ°"
icon = "ğŸ™‹"

[[pages]]
path = "pages/auth/registration_teacher.py"
name = "Ğ ĞµĞ³Ğ¸ÑÑ‚Ñ€Ğ°Ñ†Ğ¸Ñ_Ğ´Ğ»Ñ_ÑƒÑ‡Ğ¸Ñ‚ĞµĞ»Ñ"
icon = "ğŸ§‘â€ğŸ«"